// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0

package db

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type Link struct {
	ID         pgtype.UUID
	ShortCode  pgtype.Text
	FullUrl    string
	UserID     pgtype.UUID
	CreatedAt  pgtype.Timestamp
	ClickCount pgtype.Int4
}

type User struct {
	ID        pgtype.UUID
	Email     string
	Password  string
	CreatedAt pgtype.Timestamp
}
